---
#global settings
global:
  scrape_interval: 5s
  # scrape_timeout: 10s
  external_labels:
    monitor: 'infracloud-monitor'
  evaluation_interval: 5s 

#alerting settings
# alerting:
#   alertmanagers:
#   - static_configs:
#     - target:
    # - alertmanager: 9093

# rule settings
# rule_files:
#   - "first_rule.yml/rules"
#   - "second_rules.yml/.rules"

# scrape config
# metrics or the exporters that we require to get pulled
scrape_configs:
  - job_name: 'test_exporter_1'
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    scrape_interval: 5s
    static_configs:
    - targets:
      - "localhost:9393"
  # - job_name: 'test_exporter_2'
  #   metrics_path: /metrics
  #   honor_labels: false
  #   honor_timestamps: true
  #   sample_limit: 0
  #   scrape_interval: 30s
  #   static_configs:
  #   - targets:
  #     - "localhost:9393"

